# Generated by Django 5.1.7 on 2025-04-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Filedigital", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Filedigital.category",
            ),
        ),
    ]
