# Generated by Django 5.1.7 on 2025-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filedigital', '0003_alter_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FilePathField(path='C:\\Users\\user\\Desktop\\File-Digitalization\\media\\backup_documents', unique=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fileactivitylog',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('approve', 'Approve'), ('reject', 'Reject'), ('download', 'Download'), ('share', 'Share'), ('comment', 'Comment'), ('login', 'Login'), ('logout', 'Logout')], max_length=10),
        ),
    ]
